BRNGG-9087: Add helm chart
bringg/redis-operator pull request #10
Opened 2022-08-29 08:49 UTC by Shareed2k

2022-08-29 09:10 UTC, HagaiBarel requested changes
How will this be synced with the changes in the code? Manually?

2022-08-29 09:10 UTC, HagaiBarel commented on charts/redis-operator/templates/deployment.yaml
> +            - '--zap-log-level=info'
This should be configurable

2022-08-29 09:10 UTC, HagaiBarel commented on charts/redis-operator/templates/deployment.yaml
> +            - name: WATCH_NAMESPACE
This should be configurable

2022-08-29 09:10 UTC, HagaiBarel commented on charts/redis-operator/templates/deployment.yaml
> +  namespace: {{ .Values.namespace }}
This can be removed, leave it to the user to install in whatever namespace he wants using helm

2022-08-29 09:10 UTC, HagaiBarel commented on charts/redis-operator/values.yaml
> +createNamespace: true
This can be removed, the chart shouldn't create a namespace, leave it to the user

2022-08-29 09:10 UTC, HagaiBarel commented on charts/redis-operator/values.yaml
> +  tag: "v0.3.0"
this is the app version in `chart.yaml` so can be removed

2022-08-29 09:10 UTC, HagaiBarel commented on charts/redis-operator/values.yaml
> +    memory: 128Mi
```suggestion
resources: {}
```

Leave it to the user to decide

2022-08-29 09:10 UTC, HagaiBarel commented on charts/redis-operator/templates/namespace.yaml
> +{{- if .Values.createNamespace }}
This can be removed, the chart shouldn't create a namespace for the user

2022-08-29 09:11 UTC, shamil requested changes

2022-08-29 09:11 UTC, shamil commented on charts/redis-operator/templates/namespace.yaml
> +{{- if .Values.createNamespace }}
do not create namespace directly, let `helm` manage it with it's options like `--create-namespace` if namespace doesn't exist

2022-08-29 09:11 UTC, shamil commented on charts/redis-operator/values.yaml
> +createNamespace: true
remove

2022-08-29 09:11 UTC, shamil commented on charts/redis-operator/values.yaml
> +  tag: "v0.3.0"
comment this out, since you wan to take it from the chart's `appVersion`by default

2022-08-29 09:50 UTC, HagaiBarel requested changes

2022-08-29 09:50 UTC, HagaiBarel commented on charts/redis-operator/templates/deployment.yaml
> +          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```suggestion
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```

2022-08-29 09:50 UTC, HagaiBarel commented on charts/redis-operator/values.yaml
> +  tag: "v0.3.0"
This can be commented out if we're using the chart's appVersion for the image tag

2022-08-29 13:05 UTC, shamil requested changes

2022-08-29 13:05 UTC, shamil commented on charts/redis-operator/templates/clusterrolebinding.yaml
> +metadata:
add common labels

2022-08-29 13:05 UTC, shamil commented on charts/redis-operator/values.yaml
> +- --zap-log-level=info
This will restrict how args are overriden, since if someone wants to add or change env variable, he will need to provide every coomandline args, since `arrays` are not mergable.

I suggest put it back into deployment template, and just allow to override the `log-level`. In addition, you cold provide a value for `extraOperatorArgs` or something.

2022-08-30 09:38 UTC, shamil commented on charts/redis-operator/values.yaml
> +extraOperatorArgs: {}
```suggestion
extraOperatorArgs: []
```

2022-08-30 09:57 UTC, shamil requested changes

2022-08-30 09:57 UTC, shamil commented on charts/redis-operator/templates/deployment.yaml
> +          {{- end }}
I suggest to avoid having free `yaml` input, instead do a `range` loop

2022-08-31 04:24 UTC, HagaiBarel approved these changes

2022-08-31 13:36 UTC, shamil approved these changes

2022-08-31 17:07 UTC, merged